// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ace-tomorrow-night-eighties': string;
  'aceTomorrowNightEighties': string;
}
export const cssExports: CssExports;
export default cssExports;
