// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'edit-button': string;
  'editButton': string;
  'title': string;
  'title-input': string;
  'titleInput': string;
}
export const cssExports: CssExports;
export default cssExports;
