// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'container': string;
  'link': string;
  'message': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
