// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'delete-button': string;
  'deleteButton': string;
  'programs-table': string;
  'programsTable': string;
}
export const cssExports: CssExports;
export default cssExports;
