// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'big-text': string;
  'bigText': string;
  'form': string;
  'grow': string;
  'layout': string;
  'medium-text': string;
  'mediumText': string;
  'small-text': string;
  'smallText': string;
}
export const cssExports: CssExports;
export default cssExports;
