// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'heading': string;
  'layout': string;
  'programs-table': string;
  'programsTable': string;
  'section': string;
}
export const cssExports: CssExports;
export default cssExports;
