// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'error': string;
  'tab': string;
  'tab-bar': string;
  'tabBar': string;
}
export const cssExports: CssExports;
export default cssExports;
