// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button-group': string;
  'buttonGroup': string;
  'layout': string;
}
export const cssExports: CssExports;
export default cssExports;
