// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button-group': string;
  'buttonGroup': string;
  'content-area': string;
  'contentArea': string;
  'layout': string;
  'toolBarLeft': string;
}
export const cssExports: CssExports;
export default cssExports;
