// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'control': string;
  'icon-button': string;
  'iconButton': string;
  'input': string;
}
export const cssExports: CssExports;
export default cssExports;
