// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'canvas': string;
  'canvas-container': string;
  'canvasContainer': string;
  'error': string;
}
export const cssExports: CssExports;
export default cssExports;
