// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'hamburger-button': string;
  'hamburgerButton': string;
  'menu': string;
  'menu-divider': string;
  'menu-item': string;
  'menu-title': string;
  'menuDivider': string;
  'menuItem': string;
  'menuTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
