name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: npm ci
      - run: npm run check
      - run: npm run build
      - name: test
        run: |
          npm run -w server db:migrate
          npm run -w server test
        env:
          CI: true
          DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
